### ISSUE TITLE
[BUG] - Uncaught Exception: Unrecognized option "syn_config" under "crayfish_commons"

### ISSUE THREAD

**Issue by Natkeeran** [Islandora-CLAW/Crayfish#181]
**What steps does it take to reproduce the issue?**
Follow the instructions [here](https://github.com/Islandora/islandora_mirador/?tab=readme-ov-file#setting-up-hocr) to set up the action and reaction for hocr generation.  

```
NOTICE: PHP message: 2024-01-30T19:13:22+00:00 [critical] Uncaught Exception: Unrecognized option "syn_config" under "crayfish_commons". Available options are "apix_middleware_enabled", "fedora_base_uri".
2024/01/30 19:13:22 [error] 606#606: *135 FastCGI sent in stderr: "PHP message: 2024-01-30T19:13:22+00:00 [critical] Uncaught Exception: Unrecognized option "syn_config" under "crayfish_commons". Available options are "apix_middleware_enabled", "fedora_base_uri"" while reading upstream, client: 172.22.0.6, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm82/php-fpm82.sock:", host: "hypercube:8000"
172.22.0.6 - - [30/Jan/2024:19:13:22 +0000] "GET / HTTP/1.1" 500 137332 "-" "Apache-HttpClient/4.5.13 (Java/17.0.9)" "-"
```

Related Alpaca trace
```
org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking http://hypercube:8000/ with statusCode: 500
	at org.apache.camel.component.http.HttpProducer.populateHttpOperationFailedException(HttpProducer.java:362)
	at org.apache.camel.component.http.HttpProducer.process(HttpProducer.java:246)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:169)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.redeliver(RedeliveryErrorHandler.java:779)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:148)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:60)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:147)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:312)
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:141)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696)
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318)
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1237)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1227)
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1120)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
	Suppressed: org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking http://hypercube:8000/ with statusCode: 500
		... 21 common frames omitted
		Suppressed: org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking http://hypercube:8000/ with statusCode: 500
			... 21 common frames omitted
			Suppressed: org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking http://hypercube:8000/ with statusCode: 500
				... 21 common frames omitted
				Suppressed: org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking http://hypercube:8000/ with statusCode: 500
					... 21 common frames omitted
					Suppressed: org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking http://hypercube:8000/ with statusCode: 500
						at org.apache.camel.component.http.HttpProducer.populateHttpOperationFailedException(HttpProducer.java:362)
						at org.apache.camel.component.http.HttpProducer.process(HttpProducer.java:246)
						at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
						at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:169)
						at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:714)
						at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:623)
						... 16 common frames omitted
nat@LIB-6HSWM53:~/tools/isle-dc$ 

```

* When does this issue occur?
Upload a page repository item.

* Which page does it occur on?
Any new page item. 

* What happens?
The hocr text file does not get created.

* To whom does it occur (anonymous visitor, editor, administrator)?
editor/admin

* What did you expect to happen?
The hocr file to be created.  

**Which version of Islandora are you using?**
* Islandora Starter Site
* ISLE-DC  TAG=3.0.0

**Any related open or closed issues to this bug report?**

**Screenshots:**

**Comment by aOelschlager** [comment]
syn_config was removed from buildkit with [tag 3.0.0](https://github.com/Islandora-Devops/isle-buildkit/pull/299#issuecomment-1806080271) which is what you are using. Would you be able to double check that the images being used are 3.0.0? It should show that if you run docker ps.

**Comment by alxp** [comment]
I see one instance of this flag still in the config in my buiildkig 3.2.1, as I was getting the same error:



https://github.com/Islandora-Devops/islebuildkit/blob/main/hypercube/rootfs/etc/confd/templates/crayfish_commons.yaml.tmpl

Do we just need to get rid of this line? Based on the UPGRADE.md of Crayfish the replacement configs already seem to be in the Hypercube image in buildkit.

**Comment by whikloj** [comment]
If this is a buildkit specific issue, perhaps it should be under https://github.com/islandora-devops/isle-buildkit/issues
